name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Sync Repository
      run: cd /home/mosni/Software/Frontend/weatherFrontend && git pull
